// Code generated by git.repo.services.lenvendo.ru/grade-factor/go-kit-service-generator REMOVE THIS STRING ON EDIT OR DO NOT EDIT.
package sentry

import (
	"encoding/json"
	"net/http"

	"github.com/kagestonedragon/server/configs"
	"github.com/kagestonedragon/server/pkg/health"
	"github.com/getsentry/sentry-go"
	sentryhttp "github.com/getsentry/sentry-go/http"
)

// NewSentry initializes new global sentry Client.
func NewSentry(cfg *configs.Config) error {
	var debug bool
	if cfg.Logger.Level == "debug" {
		debug = true
	}
	if err := sentry.Init(sentry.ClientOptions{
		Dsn:              cfg.Sentry.Dsn,
		Debug:            debug,
		AttachStacktrace: true,
		Environment:      cfg.Sentry.Environment,
		Release:          health.Commit,
	}); err != nil {
		return err
	}
	var data map[string]interface{}
	b, err := json.Marshal(cfg)
	if err != nil {
		return err
	}
	if err := json.Unmarshal(b, &data); err != nil {
		return err
	}
	sentry.AddBreadcrumb(&sentry.Breadcrumb{
		Category: "config",
		Data:     data,
		Message:  "init config",
	})
	return nil
}

func Middleware(h http.Handler) http.Handler {
	return sentryhttp.New(sentryhttp.Options{Repanic: true}).Handle(h)
}
