// Code generated by git.repo.services.lenvendo.ru/grade-factor/go-kit-service-generator  REMOVE THIS STRING ON EDIT OR DO NOT EDIT.
package user

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"

	"github.com/go-kit/kit/log"
	"github.com/go-kit/kit/tracing/opentracing"
	httptransport "github.com/go-kit/kit/transport/http"
	"github.com/gorilla/mux"
	"github.com/gorilla/schema"
	stdopentracing "github.com/opentracing/opentracing-go"
	"github.com/pkg/errors"
)

// NewHTTPClient returns an Service backed by an HTTP server living at the
// remote instance. We expect instance to come from a service discovery system,
// so likely of the form "host:port". We bake-in certain middlewares,
// implementing the client library pattern.
func NewHTTPClient(instance string, tracer stdopentracing.Tracer, logger log.Logger) (Service, error) {
	// Quickly sanitize the instance string.
	if !strings.HasPrefix(instance, "http") {
		instance = "http://" + instance
	}
	u, err := url.Parse(instance)
	if err != nil {
		return nil, err
	}

	// global client middlewares
	var options []httptransport.ClientOption
	if tracer != nil {
		options = append(
			options,
			httptransport.ClientBefore(opentracing.ContextToHTTP(tracer, logger)),
		)
	}

	return endpoints{
		AddUserEndpoint: httptransport.NewClient(
			"POST",
			copyURL(u, "/user"),
			encodeHTTPAddUserAddUserRequest,
			decodeHTTPAddUserUser,
			options...,
		).Endpoint(),
		GetUserListEndpoint: httptransport.NewClient(
			"GET",
			copyURL(u, "/user"),
			encodeHTTPGetUserListGetUserListRequest,
			decodeHTTPGetUserListGetUserListResponse,
			options...,
		).Endpoint(),
		UpdateUserEndpoint: httptransport.NewClient(
			"PUT",
			copyURL(u, "/user/{id}"),
			encodeHTTPUpdateUserUser,
			decodeHTTPUpdateUserUpdateUserResponse,
			options...,
		).Endpoint(),
		DeleteUserByIdEndpoint: httptransport.NewClient(
			"DELETE",
			copyURL(u, "/user/{id}"),
			encodeHTTPDeleteUserByIdDeleteUserByIdRequest,
			decodeHTTPDeleteUserByIdDeleteUserByIdResponse,
			options...,
		).Endpoint(),
		GetUserByIdEndpoint: httptransport.NewClient(
			"GET",
			copyURL(u, "/user/{id}"),
			encodeHTTPGetUserByIdGetUserByIdRequest,
			decodeHTTPGetUserByIdUser,
			options...,
		).Endpoint(),
	}, nil
}

func copyURL(base *url.URL, path string) *url.URL {
	next := *base
	next.Path = path
	return &next
}

func encodeHTTPAddUserAddUserRequest(_ context.Context, r *http.Request, request interface{}) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(request); err != nil {
		return errors.Wrap(err, "encode request body")
	}
	r.Body = ioutil.NopCloser(&buf)

	return nil
}
func encodeHTTPGetUserListGetUserListRequest(_ context.Context, r *http.Request, request interface{}) error {
	{
		queryMap := make(map[string][]string)
		if err := schema.NewEncoder().Encode(request, queryMap); err == nil {
			query := url.Values(queryMap)
			r.URL.RawQuery = query.Encode()
		}
	}

	return nil
}
func encodeHTTPUpdateUserUser(_ context.Context, r *http.Request, request interface{}) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(request); err != nil {
		return errors.Wrap(err, "encode request body")
	}
	r.Body = ioutil.NopCloser(&buf)
	req := request.(*User)
	rout := mux.NewRouter()
	rout.Path(r.URL.Path).Name("UpdateUser")

	url, err := rout.Get("UpdateUser").URL(
		"id", fmt.Sprint(req.Id),
	)
	if err != nil {
		return err
	}

	r.URL.Path = url.String()

	return nil
}
func encodeHTTPDeleteUserByIdDeleteUserByIdRequest(_ context.Context, r *http.Request, request interface{}) error {
	{
		queryMap := make(map[string][]string)
		if err := schema.NewEncoder().Encode(request, queryMap); err == nil {
			query := url.Values(queryMap)
			r.URL.RawQuery = query.Encode()
		}
	}
	req := request.(*DeleteUserByIdRequest)
	rout := mux.NewRouter()
	rout.Path(r.URL.Path).Name("DeleteUserById")

	url, err := rout.Get("DeleteUserById").URL(
		"id", fmt.Sprint(req.Id),
	)
	if err != nil {
		return err
	}

	r.URL.Path = url.String()

	return nil
}
func encodeHTTPGetUserByIdGetUserByIdRequest(_ context.Context, r *http.Request, request interface{}) error {
	{
		queryMap := make(map[string][]string)
		if err := schema.NewEncoder().Encode(request, queryMap); err == nil {
			query := url.Values(queryMap)
			r.URL.RawQuery = query.Encode()
		}
	}
	req := request.(*GetUserByIdRequest)
	rout := mux.NewRouter()
	rout.Path(r.URL.Path).Name("GetUserById")

	url, err := rout.Get("GetUserById").URL(
		"id", fmt.Sprint(req.Id),
	)
	if err != nil {
		return err
	}

	r.URL.Path = url.String()

	return nil
}

func decodeHTTPAddUserUser(_ context.Context, r *http.Response) (interface{}, error) {
	if r.StatusCode != http.StatusOK {
		return nil, errors.New(r.Status)
	}
	var request User
	if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
		return nil, errors.Wrap(err, "decode request body")
	}
	return request, nil
}

func decodeHTTPGetUserListGetUserListResponse(_ context.Context, r *http.Response) (interface{}, error) {
	if r.StatusCode != http.StatusOK {
		return nil, errors.New(r.Status)
	}
	var request GetUserListResponse
	if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
		return nil, errors.Wrap(err, "decode request body")
	}
	return request, nil
}

func decodeHTTPUpdateUserUpdateUserResponse(_ context.Context, r *http.Response) (interface{}, error) {
	if r.StatusCode != http.StatusOK {
		return nil, errors.New(r.Status)
	}
	var request UpdateUserResponse
	if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
		return nil, errors.Wrap(err, "decode request body")
	}
	return request, nil
}

func decodeHTTPDeleteUserByIdDeleteUserByIdResponse(_ context.Context, r *http.Response) (interface{}, error) {
	if r.StatusCode != http.StatusOK {
		return nil, errors.New(r.Status)
	}
	var request DeleteUserByIdResponse
	if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
		return nil, errors.Wrap(err, "decode request body")
	}
	return request, nil
}

func decodeHTTPGetUserByIdUser(_ context.Context, r *http.Response) (interface{}, error) {
	if r.StatusCode != http.StatusOK {
		return nil, errors.New(r.Status)
	}
	var request User
	if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
		return nil, errors.Wrap(err, "decode request body")
	}
	return request, nil
}
