// Code generated by git.repo.services.lenvendo.ru/grade-factor/go-kit-service-generator  REMOVE THIS STRING ON EDIT OR DO NOT EDIT.
package user

type validator interface {
	Validate() error
}

func validate(req interface{}) error {
	if val, ok := interface{}(req).(validator); ok {
		if err := val.Validate(); err != nil {
			return err
		}
	}
	return nil
}
